// <auto-generated />
using System;
using Dotnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Dotnet.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Test");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bad3985d-b424-4525-a853-b57ee23dd338"),
                            Message = "Hello World!",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("b6a5c921-4645-4156-9d29-260b4aad13ea"),
                            Message = "Hello Person!",
                            Role = "Assistant"
                        },
                        new
                        {
                            Id = new Guid("68fb1957-95aa-4fc2-a892-0076b3901aa8"),
                            Message = "Goodbye!",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
